### Site info:
title: Brian E. J. Rose
tagline: Climate dynamics and modeling group at the University at Albany
author: Brian E. J. Rose
email: brose@albany.edu
description: "Brian E. J. Rose, climate dynamics group at U. Albany" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
#keywords: "Jekyll, theme, Freshman21"
baseurl: "/facstaff/brose" # the subpath of your site, e.g. /blog
url: "http://www.atmos.albany.edu/facstaff/brose" # the base hostname & protocol for your site
locale: en_US

# get rid of all smart quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]

### Personal info and site tools info:
#twitter_username: yulijia
github_username:  brian-rose
#disqus_shortname: freshman21
favicon:     "{{ site.baseurl }}/images/favicon.ico"
aboutme: Brian E. J. Rose # these are shown on aboutme-sidebar.
aboutme_photo: "http://www.atmos.albany.edu/facstaff/brose/images/Brian-Rose.png" # your photo.
#aboutme_photo: https://i.imgur.com/Mdc4szJl.jpg # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
#    cn:
#      Aboutme: "关于我"
#      Archives: "存档"
#      Blogroll: "良师益友"
#      Categories: "分类目录"
#      Copyright_Notice: "版权声明"
#      Recent_Posts: "近期文章"
#      Tags: "标签"
#      Previous: "前一页"
#      Next: "后一页"
#      PostedInCategories: "目录:"
#      Taggedwith: "| 标签:"
#      PostDate: "| 发表时间: "


### your Blogroll info, only name can shown on the page.

#Blogroll:
#    - name: Freshman21
#      href: http://yulijia.net/freshman21
#      title: Another Jekyll blog theme
#    - name: author's website
#      href: http://yulijia.net/
#      title: Lijia Yu's website


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
